### ISSUE TITLE
graalvm feature is broken due to old default values

### ISSUE THREAD

**Issue by cl-a-us** [audacioustux/devcontainers#34]
Current versions of graalvm are 21 and 23.

from version 21 onwards ther graalvm Updater is removed. With version 21 the last step in install.sh fails because "gu" ist not part of graalvm anymore.

For graalvm users it might be worth to check https://github.com/devcontainers/features/pkgs/container/features%2Fjava using  `"version": "21-graalce"`

**Comment by audacioustux** [comment]
Thanks for the PR! it's probably time to deprecate the feature..
